# The package collection to use
collection = "nightly-250120"

[install]

# Whether to install packages together with their
# sources or not. This is mainly useful for programmers
# who have set their editor up with some *go to definition*
# functionality (for instance by using idris2-lsp with neovim).
with-src   = true

# Must-have libraries. These will be installed automatically
# when using a new package collection.
libs       = [ "elab-util",
               "graph",
               "prim",
               "sop",
               "tailrec" ]

# Must-have applications. These will be installed automatically
# when using a new package collection.
apps       = [ "idris2-lsp" ]

safety-prompt = false

[idris2]

# Whether to build Idris2 with its bootstrap compiler.
# Bootstrapping takes longer than building with an existing
# Idris2 installation, but it will work even if the existing
# Idris2 compiler is outdated.
bootstrap  = false

# Name or path to the scheme executable to use.
scheme     = "chez"

repl.rlwrap = true

# Below are some examples for custom packages

# A local package to be available with all
# package collections.
# [custom.all.chem]
# type = "local"
# path = "/home/hock/idris/chem"
# ipkg = "chem.ipkg"

# A package on GitHub to be available with all
# package collections.
# [custom.all.foo]
# type = "github"
# path = "https://github.com/bar/foo"
# ipkg = "foo.ipkg"

# Override library `toml` from package collection `nightly-220503`
# by using a custom commit hash.
# [custom.nightly-220503.toml]
# type   = "github"
# url    = "https://github.com/cuddlefishie/toml-idr"
# commit = "eb7a146f565276f82ebf30cb6d5502e9f65dcc3c"
# ipkg   = "toml.ipkg"

[log]
exec = "build"
run = "build"
test = "build"
repl = "build"
